#cloud-config
users:
  - name: automatizacion
    ssh-authorized-keys:
      - ssh-rsa AAAAD
    passwd: $6$xRqgFBRZlWy$3
    sudo: ALL=(ALL) NOPASSWD:ALL
    lock_passwd: false
    shell: /bin/bash
    
packages:
  - htop
  - rsyslog
